---
- hosts: all
  become: true
  tasks:
    - name: Run Prerequisites
      include_tasks: playbooks/prerequisites.yml

- hosts: server_initial
  become: true
  tasks:
    - name: Initialise first server in cluster
      include_tasks: playbooks/k3s_nodes/server_initial.yml

- hosts: server_additional
  become: true
  tasks:
    - name: Initialise additional servers and add to cluster
      include_tasks: playbooks/k3s_nodes/server_additional.yml

- hosts: agents
  become: true
  tasks:
    - name: Initialise Agent Node
      include_tasks: playbooks/k3s_nodes/agent.yml